<?php 
	/** @var \UIComponents\View\Helper\Bootstrap $oBootstrap **/
	$oBootstrap = $this->Bootstrap();
	/** @var \UIComponents\View\Helper\Components $oComponents **/
	$oComponents = $this->Components();
	/** @var \Admin\Entity\User $oUser **/
	$oUser = $this->zfcUserIdentity();
?>
<h4>Single Button</h4>
<div class="clearfix well"><?php echo $oComponents->Button(); ?></div>
<div class="clearfix well"><?php echo $oComponents->Button(array('label' => 'click here ^^')); ?></div>

<hr />
<h4>Simple Button Group</h4>
<div class="clearfix well"><?php 

$btn1 = $oComponents->Button(array('label' => 'button 1', 'type' => 'primary'))->render();
$btn2 = $oComponents->Button(array('label' => 'button 2', 'tagname' => 'button'))->render();
$btn3 = $oComponents->Button(array('label' => 'button 3', 'disabled' => 'disabled'))->render();

echo $oComponents->ButtonGroup(array(
	'buttons' => array( 
		$btn1, $btn2, $btn3, 
	)	
)); 

 ?></div>

<hr />
<h4>Different Setup Button Group</h4>
<div class="clearfix well"><?php echo $oComponents->ButtonGroup(array(
	'block' => true,
	'vertical' => true,
	'buttons' => array( 
		$oComponents->Button(array('label' => 'button 1', 'type' => 'warning')), 
		$oComponents->Button(array('label' => 'button 2', 'tagname' => 'button', 'disabled' => 'disabled')),
		$oComponents->Button(array('label' => 'button 3', 'block' => true)), 
	)	
)); ?></div>

