<h3>[MyApplication] UI Components</h3>

<p><?= $this->translate('see the integrated UI components in action...'); ?></p>

<h4><?= $this->translate('test pages'); ?></h4>

<ul>
    <li>
        <p><a href="<?= $this->url('uicomponentstestpages/default', array('action' => 'panels')) ?>"><?= $this->translate('panels'); ?></a>
    </li>
    <li>
        <p><a href="<?= $this->url('uicomponentstestpages/default', array('action' => 'controls')) ?>"><?= $this->translate('controls'); ?></a>
    </li>
    <li>
        <p><a href="<?= $this->url('uicomponentstestpages/default', array('action' => 'forms')) ?>"><?= $this->translate('forms'); ?></a>
    </li>
    <li>
        <p><a href="<?= $this->url('uicomponentstestpages/default', array('action' => 'tables')) ?>"><?= $this->translate('tables'); ?></a>
    </li>
    <li>
        <p><a href="<?= $this->url('uicomponentstestpages/default', array('action' => 'widgets')) ?>"><?= $this->translate('widgets'); ?></a>
    </li>
</ul>